spring:
  config:
    import: sm://database-password
  application:
    name: secret-manager
  cloud:
    gcp:
      project-id: default-test-481600
      secretmanager.enabled: true

gcp-pwd: ${sm://projects/795119892706/secrets/database-password}